import { StyleSheet } from "react-native";

import type { AppThemeColors } from "@/lib/app-theme";
import { screenScrollContent } from "@/constants/screen-layout";

export function createQiblaStyles(c: AppThemeColors) {
  return StyleSheet.create({
    background: { flex: 1 },
    safe: { flex: 1, backgroundColor: "transparent" },
    scroll: { flex: 1 },
    scrollContent: { ...screenScrollContent, paddingTop: 8 },
    sectionLabel: {
      fontSize: 20,
      fontFamily: "PlusJakartaSans-SemiBold",
      color: c.text,
      marginBottom: 12,
    },
    sectionDivider: {
      height: 1,
      backgroundColor: c.divider,
      marginVertical: 12,
    },
    prayerSection: { marginBottom: 32 },
    prayerCard: {
      backgroundColor: c.usesBackgroundImage ? "transparent" : c.card,
      borderRadius: 20,
      paddingVertical: 16,
      paddingHorizontal: 20,
      paddingLeft: 22,
      borderLeftWidth: 3,
      borderLeftColor: c.accentBorder,
    },
    prayerCardHeader: {
      marginBottom: 16,
      paddingBottom: 14,
      borderBottomWidth: 1,
      borderBottomColor: c.divider,
    },
    prayerCardMethod: {
      fontSize: 11,
      fontFamily: "PlusJakartaSans-Medium",
      color: c.textMuted,
      marginBottom: 4,
    },
    prayerCardHijri: {
      fontSize: 14,
      fontFamily: "PlusJakartaSans-SemiBold",
      color: c.text,
      marginBottom: 2,
    },
    prayerCardGregorian: {
      fontSize: 12,
      fontFamily: "PlusJakartaSans-Regular",
      color: c.textMuted,
      marginBottom: 4,
    },
    prayerCardCoords: { flexDirection: "row", alignItems: "center", gap: 4 },
    prayerCardCoordsText: {
      fontSize: 11,
      fontFamily: "PlusJakartaSans-Regular",
      color: c.textMuted,
    },
    prayerCardRemaining: {
      fontSize: 13,
      fontFamily: "PlusJakartaSans-Medium",
      color: c.textMuted,
      marginTop: 6,
    },
    prayerRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      paddingVertical: 16,
      paddingHorizontal: 8,
      marginHorizontal: -6,
      borderBottomWidth: 1,
      borderBottomColor: c.divider,
      position: "relative",
    },
    prayerRowCurrent: {
      backgroundColor: c.accentSurface,
      borderRadius: 12,
      marginHorizontal: 0,
      paddingHorizontal: 14,
      paddingVertical: 18,
    },
    prayerRowLeft: { flex: 1, marginRight: 44 },
    prayerRowTimeRow: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 6 },
    prayerRowLabel: {
      fontSize: 16,
      fontFamily: "PlusJakartaSans-Medium",
      color: c.text,
    },
    prayerLabelDone: {
      textDecorationLine: "line-through",
      color: c.textMuted,
    },
    prayerRowTime: {
      fontSize: 14,
      fontFamily: "PlusJakartaSans-Regular",
      color: c.textMuted,
    },
    prayerRowCurrentDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: c.accent,
    },
    prayerRowCheckboxWrap: { position: "absolute", right: 0, top: 16 },
    prayerRowLast: { borderBottomWidth: 0 },
    prayerRowPressed: { opacity: 0.7 },
    prayerCheckbox: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: c.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    prayerCheckboxChecked: {
      backgroundColor: c.accent,
      borderColor: c.accent,
    },
    prayerNextLabel: {
      fontSize: 9,
      fontFamily: "PlusJakartaSans-Medium",
      color: c.textMuted,
      letterSpacing: 0.3,
      marginBottom: 2,
    },
    prayerNextWidgetRow: { flexDirection: "row", alignItems: "center" },
    prayerNextText: {
      fontSize: 14,
      fontFamily: "PlusJakartaSans-SemiBold",
      color: c.text,
      marginLeft: 6,
    },
    prayerNextCountdown: {
      fontSize: 16,
      fontFamily: "PlusJakartaSans-Bold",
      color: c.text,
      letterSpacing: 0.5,
    },
    prayerCardFooter: {
      fontSize: 10,
      fontFamily: "PlusJakartaSans-Regular",
      color: c.textMuted,
      marginTop: 10,
      textAlign: "center",
    },
    prayerUnavailable: {
      fontSize: 14,
      fontFamily: "PlusJakartaSans-Regular",
      color: c.textMuted,
      paddingVertical: 12,
    },
    qiblaSubtitle: {
      fontSize: 14,
      fontFamily: "PlusJakartaSans-Regular",
      color: c.textMuted,
      textAlign: "center",
      marginBottom: 20,
    },
    directionLabel: {
      fontSize: 40,
      fontFamily: "PlusJakartaSans-Bold",
      color: c.accent,
    },
    degreeLabel: {
      fontSize: 22,
      fontFamily: "PlusJakartaSans-SemiBold",
      color: c.text,
    },
    compassCircle: {
      borderWidth: 3,
      borderColor: c.accentBorder,
      backgroundColor: c.cardElevated,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: c.isDark ? 0.35 : 0.06,
      shadowRadius: 8,
      elevation: 6,
    },
    northDot: {
      position: "absolute",
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: c.isDark ? "rgba(255,255,255,0.35)" : "rgba(0, 0, 0, 0.2)",
    },
    needle: {
      backgroundColor: c.accent,
      position: "absolute",
      bottom: 0,
    },
    qiblaAngle: {
      marginTop: 24,
      fontSize: 16,
      fontFamily: "PlusJakartaSans-Medium",
      color: c.textMuted,
    },
    compassErrorText: {
      fontSize: 16,
      fontFamily: "PlusJakartaSans-Medium",
      color: c.danger,
      textAlign: "center",
      marginBottom: 8,
    },
    qiblaSection: { paddingTop: 8, alignItems: "center" },
    infoRow: {
      flexDirection: "row",
      alignItems: "baseline",
      gap: 16,
      marginBottom: 24,
    },
    needleWrapper: {
      position: "absolute",
      top: "50%",
      left: "50%",
      alignItems: "center",
      justifyContent: "center",
    },
    prayerNextWidget: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 10,
    },
    prayerNextWidgetLeft: { flex: 1 },
    compassError: { alignItems: "center", paddingVertical: 24 },
  });
}
