import { StyleSheet } from "react-native";

import type { AppThemeColors } from "@/lib/app-theme";
import { MIN_TOUCH_TARGET } from "@/lib/ui/spacing";

export function createToolScreenStyles(c: AppThemeColors) {
  return StyleSheet.create({
    section: {
      marginBottom: 24,
    },
    sectionLabel: {
      fontSize: 12,
      fontFamily: "PlusJakartaSans-SemiBold",
      color: c.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.4,
      marginBottom: 10,
    },
    field: {
      marginBottom: 20,
      gap: 6,
    },
    fieldLabel: {
      fontSize: 13,
      fontFamily: "PlusJakartaSans-SemiBold",
      color: c.textMuted,
    },
    input: {
      fontSize: 17,
      fontFamily: "PlusJakartaSans-SemiBold",
      color: c.text,
      paddingVertical: 10,
      paddingHorizontal: 0,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
      backgroundColor: "transparent",
    },
    inputMuted: {
      fontSize: 16,
      fontFamily: "PlusJakartaSans-Regular",
    },
    chipRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
    },
    chip: {
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      backgroundColor: "transparent",
      minHeight: MIN_TOUCH_TARGET - 4,
      justifyContent: "center",
      alignItems: "center",
    },
    chipActive: {
      backgroundColor: c.accent,
      borderColor: c.accent,
    },
    chipText: {
      fontSize: 14,
      fontFamily: "PlusJakartaSans-SemiBold",
      color: c.text,
    },
    chipTextActive: {
      color: c.onAccent,
    },
    segmentRow: {
      flexDirection: "row",
      gap: 10,
      marginBottom: 16,
    },
    segment: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      backgroundColor: "transparent",
      alignItems: "center",
      justifyContent: "center",
      minHeight: MIN_TOUCH_TARGET,
    },
    highlight: {
      paddingVertical: 20,
      marginBottom: 20,
      alignItems: "center",
      gap: 6,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.divider,
    },
    highlightLabel: {
      fontSize: 12,
      fontFamily: "PlusJakartaSans-Medium",
      color: c.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.35,
    },
    highlightValue: {
      fontSize: 34,
      fontFamily: "PlusJakartaSans-Bold",
      color: c.accent,
    },
    highlightValueText: {
      fontSize: 17,
      fontFamily: "PlusJakartaSans-SemiBold",
      color: c.text,
      textAlign: "center",
      lineHeight: 24,
    },
    highlightSub: {
      fontSize: 14,
      fontFamily: "PlusJakartaSans-Regular",
      color: c.textMuted,
    },
    list: {
      marginBottom: 24,
    },
    listRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.divider,
    },
    listRowLabel: {
      flex: 1,
      fontSize: 16,
      fontFamily: "PlusJakartaSans-Medium",
      color: c.text,
    },
    listRowValue: {
      fontSize: 15,
      fontFamily: "PlusJakartaSans-SemiBold",
      color: c.textMuted,
    },
    progressTrack: {
      height: 6,
      borderRadius: 3,
      backgroundColor: c.divider,
      overflow: "hidden",
      marginBottom: 8,
    },
    progressFill: {
      height: "100%",
      borderRadius: 3,
      backgroundColor: c.accent,
    },
    body: {
      fontSize: 15,
      fontFamily: "PlusJakartaSans-Regular",
      color: c.text,
      lineHeight: 22,
      marginBottom: 16,
    },
    note: {
      fontSize: 13,
      fontFamily: "PlusJakartaSans-Regular",
      color: c.textMuted,
      lineHeight: 20,
      marginTop: 8,
    },
    primaryBtn: {
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      minHeight: MIN_TOUCH_TARGET,
      backgroundColor: c.accent,
      marginTop: 8,
    },
    primaryBtnText: {
      fontSize: 16,
      fontFamily: "PlusJakartaSans-SemiBold",
      color: c.onAccent,
    },
    ghostBtn: {
      alignSelf: "center",
      paddingVertical: 12,
      paddingHorizontal: 24,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      minHeight: MIN_TOUCH_TARGET,
      justifyContent: "center",
      marginTop: 8,
    },
    ghostBtnText: {
      fontSize: 15,
      fontFamily: "PlusJakartaSans-Medium",
      color: c.text,
    },
    counterZone: {
      alignItems: "center",
      paddingVertical: 36,
      marginBottom: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.divider,
    },
    counterValue: {
      fontSize: 64,
      fontFamily: "PlusJakartaSans-Bold",
      lineHeight: 72,
      color: c.accent,
    },
    counterHint: {
      fontSize: 14,
      fontFamily: "PlusJakartaSans-Medium",
      color: c.textMuted,
      marginTop: 8,
    },
    asmaRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.divider,
    },
    asmaIndex: {
      width: 28,
      fontSize: 14,
      fontFamily: "PlusJakartaSans-Bold",
      color: c.accent,
      textAlign: "center",
    },
    presetChip: {
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      backgroundColor: "transparent",
      marginRight: 8,
    },
    stepper: {
      flexDirection: "row",
      alignItems: "center",
      gap: 20,
    },
    stepBtn: {
      width: 44,
      height: 44,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      backgroundColor: "transparent",
      alignItems: "center",
      justifyContent: "center",
    },
    stepBtnText: {
      fontSize: 22,
      fontFamily: "PlusJakartaSans-Medium",
      color: c.text,
    },
    stepValue: {
      fontSize: 28,
      fontFamily: "PlusJakartaSans-Bold",
      color: c.text,
      minWidth: 48,
      textAlign: "center",
    },
  });
}
